site_name: 'KB OpenStack mitaka/newton'
pages:
- --== Content ==--: 'content.md'
- ------------------- Network -------------------:
   - 'Network': 'network-common.md'
- ---------------- Open vswitch ----------------:
   - 'OVS': 'openvswitch.md'
- ------------------- Neutron -------------------:
   - 'Neutron common': 'neutron/neutron-common.md'
   - 'Neutron virtual switching': 'neutron/neutron-switching.md'
   - 'Neutron ML2 plugin configuration': 'neutron/neutron-ml2config.md'
   - 'Neutron DVR': 'neutron/neutron-dvr.md'
   - 'Neutron troubleshooting': 'neutron/neutron-troubleshooting.md'
- ------------------- Hosting -------------------:
   - 'OVH': 'hosting/deploy-on-ovh.md'
- ------------- OpenStack Provider -------------:
   - 'Fuel.9':
     - 'Neutron': 'providers/fuel.9.md'
   - 'OSA.14.05':
     - 'Neutron': 'providers/osa.14.05.md'

theme: readthedocs