site_name: 'KB OpenStack mitaka/newton'
pages:
- --== Content ==--: 'content.md'
- ------------------- Network -------------------:
   - 'Network': 'network-common.md'
- ---------------- Open vswitch ----------------:
   - 'OVS': 'openvswitch.md'
- ------------------- Neutron -------------------:
   - 'Neutron common': 'neutron-common.md'
   - 'Neutron virtual switching': 'neutron-switching.md'
   - 'Neutron DVR': 'neutron-dvr.md'

theme: readthedocs