site_name: 'KB OpenStack mitaka/newton'
pages:
- ------------------- Network -------------------:
   - 'Network': 'network/network-common.md'
- ---------------- Open vswitch ----------------:
   - 'OVS': 'network/openvswitch.md'
- ------------------- Neutron -------------------:
   - 'Neutron common': 'neutron/neutron-common.md'
   - 'Neutron virtual switching': 'neutron/neutron-switching.md'
   - 'Neutron ML2 plugin configuration': 'neutron/neutron-ml2config.md'
   - 'Neutron OVS configuration': 'neutron/neutron-ovs.md'
   - 'Neutron DVR': 'neutron/neutron-dvr.md'
   - 'Neutron troubleshooting': 'neutron/neutron-troubleshooting.md'
- ------------------- Hosting -------------------:
   - 'OVH': 'hosting/deploy-on-ovh.md'
- ------------ OpenStack Provider ------------:
   - 'Fuel-9':
     - 'Neutron-DVR investigation': 'providers/fuel-9.md'
   - 'OSA-14':
     - 'Neutron-DVR investigation': 'providers/osa-14.md'
- ---- OpenStack Roles and Permitions -----:
   - 'Roles': 'os-roles.md'
- ----------- Multi-tenancy -----------:
   - 'Nova+Cinder': 'multitenancy.md'
   - 'Cinder': 'cinder.md'
   - 'Swift': 'swift.md'

theme: readthedocs