site_name: 'KB OpenStack mitaka/newton'
pages:
- ------------------- Network -------------------:
   - 'Network': 'network/network-common.md'
- ---------------- Open vswitch ----------------:
   - 'OVS': 'network/openvswitch.md'
- ------------------- Neutron -------------------:
   - 'Neutron common': 'neutron/neutron-common.md'
   - 'Neutron virtual switching': 'neutron/neutron-switching.md'
   - 'Neutron ML2 plugin configuration': 'neutron/neutron-ml2config.md'
   - 'Neutron OVS configuration': 'neutron/neutron-ovs.md'
   - 'Neutron DVR': 'neutron/neutron-dvr.md'
   - 'Neutron troubleshooting': 'neutron/neutron-troubleshooting.md'
- ------------------- Cinder -------------------:
   - 'Cinder': 'cinder/cinder.md'
- ------------------- Swift -------------------:
   - 'Swift common': 'swift/swift-common.md'
   - 'Swift rings': 'swift/swift-rings.md'
   - 'Swift configuring': 'swift/swift-configuring.md'
   - 'Swift-quotas-cli': 'swift/swift-quotas-cli.md'
- ----------- Multi-tenancy -----------:
   - 'Nova+Cinder': 'multitenancy/multitenancy.md'
   - 'OpenStack Roles and Permitions': 'multitenancy/os-roles.md'
- ------------------- Hosting -------------------:
   - 'OVH': 'hosting/deploy-on-ovh.md'
- ------------ OpenStack Provider ------------:
   - 'Fuel-9':
     - 'Neutron-DVR investigation': 'providers/fuel-9-network-features.md'
   - 'OSA-14':
     - 'Neutron-DVR investigation': 'providers/osa-14-network-features.md'

theme: readthedocs